
name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  tryhackme-badge-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "J2157"  # Your TryHackMe username
          image_path: "./assets/thm_badge.png"  # Path to save the image
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
