name: Update TryHackMe Badge
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual runs
jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download TryHackMe Badge
        run: |
          curl -o ./assets/thm_badge.png "https://tryhackme-badges.s3.amazonaws.com/$(echo '${{ secrets.THM_USERNAME }}' | tr '[:upper:]' '[:lower:]').png"
      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ./assets/thm_badge.png
          git commit -m "Update THM badge" || echo "No changes to commit"
          git push
